---
title: "Final Project Code"
output: pdf_document
---
```{r}
install.packages("NHANES")
library(NHANES)
install.packages("dplyr")
library(dplyr)
packageurl <- "https://cran.r-project.org/src/contrib/Archive/pbkrtest/pbkrtest_0.4-4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
install.packages("car", dependencies=TRUE)
library(car)
install.packages("MASS")
library(MASS)
install.packages("leaps")
library(leaps)
```


```{r}
# Initial Data Filtering
data <- NHANES %>%
  group_by(ID) %>%
  filter(n() == 1)

data <- data %>%
  mutate(
    PhysActiveDays = ifelse(PhysActive == "No", 0, PhysActiveDays),
    AlcoholDay = ifelse(is.na(Alcohol12PlusYr), 0, AlcoholDay),
  )

data <- subset(as.data.frame(data), 
              select = c(DaysPhysHlthBad, PhysActiveDays, AlcoholDay, SleepHrsNight, Smoke100n, HardDrugs, PhysActive, Marijuana, SleepTrouble, Alcohol12PlusYr))
data <- na.omit(data)
data <- filter(data, DaysPhysHlthBad > 0)
set.seed(302)
s <- sample(1:nrow(data), 303 , replace=F) 
train <- data[s ,]
test <- data[-s,]
summary(data$DaysPhysHlthBad)
```

```{r}
# Exploratory Data Analysis
summary(data$DaysPhysHlthBad)
summary(data$PhysActiveDays)
summary(data$AlcoholDay)
summary(data$SleepHrsNight)
summary(data$Smoke100n)
summary(data$HardDrugs)
summary(data$PhysActive)
summary(data$Marijuana)
summary(data$SleepTrouble)
summary(data$Alcohol12PlusYr)
```


```{r}
par(mfrow=c(2, 2))
# Initial Model Building and Assumption Checking
model_train = lm(DaysPhysHlthBad ~ PhysActiveDays + AlcoholDay + SleepHrsNight + Smoke100n + HardDrugs + PhysActive + Marijuana + SleepTrouble + Alcohol12PlusYr, data = train)
summary(model_train)
y_hat <- fitted(model_train)
e_hat <- resid(model_train)
plot(x = y_hat, y = train$DaysPhysHlthBad, main="Response vs. Fitted of the Initial Model", xlab="Fitted", ylab="DaysPhysHlthBad")
abline(a=0, b=1, lty=2)
qqnorm(e_hat, main = "Normal QQ Plot of the Initial Model")
qqline(e_hat)

# Model Transform and Assumptions Checking
train$LogDaysPhysHlthBad = log(train$DaysPhysHlthBad)
transformed_model <- lm(LogDaysPhysHlthBad ~ PhysActiveDays + AlcoholDay + SleepHrsNight + Smoke100n + HardDrugs + PhysActive + Marijuana + SleepTrouble + Alcohol12PlusYr, data = train)
y_hat <- fitted(transformed_model)
e_hat <- resid(transformed_model)
plot(x = y_hat, y = train$LogDaysPhysHlthBad, main="Response vs. Fitted of \n the Transformed Model", xlab="Fitted", ylab="LogDaysPhysHlthBad")
abline(a=0, b=1, lty=2)
qqnorm(e_hat, main = "Normal QQ Plot of the Transformed Model")
qqline(e_hat)
boxCox(model_train)
```


```{r}
# Model Selection
aicdata <- dplyr::select(train, -DaysPhysHlthBad)
stepAIC(lm(LogDaysPhysHlthBad ~ ., data=aicdata), direction = "both", k=2)
best <- regsubsets(LogDaysPhysHlthBad ~ PhysActiveDays + AlcoholDay + SleepHrsNight + Smoke100n + HardDrugs + PhysActive + Marijuana + SleepTrouble + Alcohol12PlusYr, data = train, nbest = 1, nvmax = 5)
summary(best)
```

```{r}
par(mfrow=c(1, 2))
# Assumption Checking of the First Reduced Model
reduced_model = lm(LogDaysPhysHlthBad ~ PhysActiveDays + Smoke100n + PhysActive + SleepTrouble + Alcohol12PlusYr, data = train)
anova(reduced_model, transformed_model)
y_hat <- fitted(reduced_model)
e_hat <- resid(reduced_model)
plot(x = y_hat, y = train$LogDaysPhysHlthBad, main="Response vs. Fitted of the First Reduced Model", xlab="Fitted", ylab="LogDaysPhysHlthBad")
abline(a=0, b=1, lty=2)
qqnorm(e_hat, main = "Normal QQ Plot of the First Reduced Model")
qqline(e_hat)
```

```{r}
par(mfrow=c(1, 2))
# Assumption Checking of the Second Reduced Model
reduced_model2 = lm(LogDaysPhysHlthBad ~ AlcoholDay + SleepHrsNight + Smoke100n + PhysActive + SleepTrouble, data = train)
anova(reduced_model2, transformed_model)
y_hat <- fitted(reduced_model2)
e_hat <- resid(reduced_model2)
plot(x = y_hat, y = train$LogDaysPhysHlthBad, main="Response vs. Fitted of \n the Second Reduced Model", xlab="Fitted", ylab="LogDaysPhysHlthBad")
abline(a=0, b=1, lty=2)
qqnorm(e_hat, main = "Normal QQ Plot of \n the Second Reduced Model")
qqline(e_hat)
```

```{r}
par(mfrow=c(1, 2))
# Assumption Checking of the Third Reduced Model
reduced_model3 = lm(LogDaysPhysHlthBad ~ SleepHrsNight + HardDrugs + Smoke100n + PhysActive + SleepTrouble, data = train)
anova(reduced_model3, transformed_model)
y_hat <- fitted(reduced_model3)
e_hat <- resid(reduced_model3)
plot(x = y_hat, y = train$LogDaysPhysHlthBad, main="Response vs. Fitted of \n the Third Reduced Model", xlab="Fitted", ylab="LogDaysPhysHlthBad")
abline(a=0, b=1, lty=2)
qqnorm(e_hat, main = "Normal QQ Plot of \n the Third Reduced Model")
qqline(e_hat)
```

```{r}
par(mfrow=c(1, 2))
# Assumption Checking of the Fourth Reduced Model
reduced_model4 = lm(LogDaysPhysHlthBad ~ Marijuana + PhysActiveDays + Smoke100n + PhysActive + SleepTrouble, data = train)
anova(reduced_model4, transformed_model)
y_hat <- fitted(reduced_model4)
e_hat <- resid(reduced_model4)
plot(x = y_hat, y = train$LogDaysPhysHlthBad, main="Response vs. Fitted of \n the Fourth Reduced Model", xlab="Fitted", ylab="LogDaysPhysHlthBad")
abline(a=0, b=1, lty=2)
qqnorm(e_hat, main = "Normal QQ Plot of \n the Fourth Reduced Model")
qqline(e_hat)
```

```{r}
# Four Reduced Model Evaluation
n = nrow(train)
cbind(summary(reduced_model)$adj.r.squared, extractAIC(reduced_model, k=2)[2], extractAIC(reduced_model, k=log(n))[2])
vif(reduced_model)
cbind(summary(reduced_model2)$adj.r.squared, extractAIC(reduced_model2, k=2)[2], extractAIC(reduced_model2, k=log(n))[2])
vif(reduced_model2)
cbind(summary(reduced_model3)$adj.r.squared, extractAIC(reduced_model3, k=2)[2], extractAIC(reduced_model3, k=log(n))[2])
vif(reduced_model3)
cbind(summary(reduced_model4)$adj.r.squared, extractAIC(reduced_model4, k=2)[2], extractAIC(reduced_model4, k=log(n))[2])
vif(reduced_model4)

final_model = reduced_model
par(mfrow=c(1, 2))
y_hat <- fitted(final_model)
e_hat <- resid(final_model)
plot(x = y_hat, y = train$LogDaysPhysHlthBad, main="Response vs. Fitted \n of the Final Model", xlab="Fitted", ylab="LogDaysPhysHlthBad")
abline(a=0, b=1, lty=2)
qqnorm(e_hat, main = "Normal QQ Plot of the Final Model")
qqline(e_hat)
```

```{r}
# Problematic Observation Identification
probobs <- function(model, data){ 
  n <- nrow(data)
  p <- length(coef(model))-1
  h_cut <- 2*(p+1)/n # leverage cutoff
  print("Leverage")
  print(which(hatvalues(model) > h_cut))
  print("outliers")
  print(which(rstandard(model) > 4 | rstandard(model) < -4)) 
  D_cut <- qf(0.5, p+1, n-p-1) # cooks cutoff
  print("Cooks")
  print(which(cooks.distance(model) > D_cut))
  fits_cut <- 2*sqrt((p+1)/n) # DFFITS cutoff
  print("DFFITS")
  print(which(abs(dffits(model)) > fits_cut)) 
  beta_cut <- 2/sqrt(n) # DFBETAS cutoff
  for(i in 1:(p+1)){
    print(paste0("Beta ", i-1))
    print(which(abs(dfbetas(model)[,i]) > beta_cut)) 
  }
}
probobs(final_model, train)
```

```{r}
# Model Inference
summary(final_model)
confint(final_model)
```

```{r}
par(mfrow=c(1, 2))
# Model Validation
test$LogDaysPhysHlthBad = log(test$DaysPhysHlthBad)
model_test = lm(LogDaysPhysHlthBad ~ PhysActiveDays + Smoke100n + PhysActive + SleepTrouble + Alcohol12PlusYr, data = test)
summary(final_model)
summary(model_test)

y_hat <- fitted(model_test)
e_hat <- resid(model_test)
plot(x = y_hat, y = test$LogDaysPhysHlthBad, main="Response vs. Fitted of \n the Test Model", xlab="Fitted", ylab="LogDaysPhysHlthBad")
qqnorm(e_hat, main = "Normal QQ Plot of \n the Test Model")
qqline(e_hat)

vif(final_model)
vif(model_test)

probobs(model_test, test)
```

